=== DbKeeperNet/DbKeeperNet/DbKeeperNet.Engine/Resources/Updates-1.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd" elementFormDefault="unqualified" xmlns="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd" xmlns:mstns="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
  <xs:element name="Updates">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Update" type="UpdateType" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="DefaultPreconditions" type="UpdatePreconditionCollectionType" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="AssemblyName" type="UpdateAssemblyNameType" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:complexType name="UpdateDbStepType">
    <xs:complexContent>
      <xs:extension base="UpdateStepBaseType">
        <xs:sequence>
          <xs:element name="AlternativeStatement" type="UpdateDbAlternativeStatementType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="UpdateDbAlternativeStatementType">
    <xs:simpleContent>
      <xs:extension base="UpdateDbStatementType">
        <xs:attribute name="Driver" type="xs:string" use="optional" default="all" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="UpdateType">
    <xs:sequence>
      <xs:element name="UpdateStep" type="UpdateStepBaseType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="Version" type="UpdateVersionType" use="required" />
    <xs:attribute name="FriendlyName" type="UpdateFriendlyNameType" />
  </xs:complexType>
  <xs:complexType name="CustomUpdateStepType">
    <xs:complexContent>
      <xs:extension base="UpdateStepBaseType">
        <xs:sequence>
          <xs:element name="Param" type="CustomUpdateStepParamType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="Type" type="UpdateClassType" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="UpdateStepBaseType" abstract="true">
    <xs:sequence>
      <xs:element name="Preconditions" type="UpdatePreconditionCollectionType" />
    </xs:sequence>
    <xs:attribute name="Id" type="UpdateStepIdType" use="required" />
    <xs:attribute name="FriendlyName" type="UpdateFriendlyNameType" use="optional" />
    <xs:attribute name="MarkAsExecuted" type="xs:boolean" default="true" />
  </xs:complexType>
  <xs:complexType name="PreconditionType">
    <xs:sequence>
      <xs:element name="Param" type="PreconditionParamType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="FriendlyName" type="UpdateFriendlyNameType" />
    <xs:attribute name="Precondition" type="xs:string" use="optional" default="NotExecuted" />
  </xs:complexType>
  <xs:simpleType name="UpdateAssemblyNameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
      <xs:maxLength value="64" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateVersionType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
      <xs:maxLength value="32" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateClassType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateStepIdType">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateDbStatementType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateFriendlyNameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="UpdatePreconditionCollectionType">
    <xs:sequence>
      <xs:element name="Precondition" type="PreconditionType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PreconditionParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Name" type="xs:string" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CustomUpdateStepParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Name" type="xs:string" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== DbKeeperNet/DbKeeperNet/DbKeeperNet.Engine.Windows/Extensions/DatabaseServices/OracleDatabaseServiceInstall.xml
<?xml version="1.0" encoding="utf-8" ?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd"
                	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	              xsi:schemaLocation="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd Updates-1.0.xsd"
                AssemblyName="DbKeeperNet.Engine">
  <DefaultPreconditions>
    <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
  </DefaultPreconditions>
  <Update Version="1.00">
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_assembly" Id="1"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_assembly not found" Precondition="DbTableNotFound">
          <Param>DBKEEPERNET_ASSEMBLY</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[
		CREATE table "DBKEEPERNET_ASSEMBLY" (
			"ID"         NUMBER(10,0) NOT NULL,
			"ASSEMBLY"   VARCHAR(255) NOT NULL,
			"CREATED"    DATE NOT NULL,
			CONSTRAINT "UQ_dbkeepernet_assembly" UNIQUE ("ASSEMBLY"),
			constraint  "PK_dbkeepernet_assembly" primary key ("ID")
		)
		]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create sequence DBKEEPERNET_ASSEMBLY_SEQ" Id="2"
            MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Sequence DBKEEPERNET_ASSEMBLY_SEQ not found" Precondition="OraDbSequenceNotFound">
          <Param>DBKEEPERNET_ASSEMBLY_SEQ</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[CREATE sequence "DBKEEPERNET_ASSEMBLY_SEQ"]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create trigger BI_DBKEEPERNET_ASSEMBLY" Id="3"
            MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Trigger BI_DBKEEPERNET_ASSEMBLY not found" Precondition="DbTriggerNotFound">
          <Param>BI_DBKEEPERNET_ASSEMBLY</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[
		CREATE trigger "BI_DBKEEPERNET_ASSEMBLY"  
		  before insert on "DBKEEPERNET_ASSEMBLY"              
		  for each row 
			begin  
				select "DBKEEPERNET_ASSEMBLY_SEQ".nextval into :NEW.ID from dual;
			end;
		]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_version" Id="4"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_version not found" Precondition="DbTableNotFound">
          <Param>DBKEEPERNET_VERSION</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="Oracle">
      <![CDATA[
        CREATE TABLE "DBKEEPERNET_VERSION"
        (
			"ID"         NUMBER(10,0) NOT NULL,
			"DBKEEPERNET_ASSEMBLY_ID" NUMBER(10,0) NOT NULL,
			"VERSION" varchar(32) not null,
			"CREATED" date not null,
			CONSTRAINT "UQ_dbkeepernet_version" UNIQUE ("DBKEEPERNET_ASSEMBLY_ID", "VERSION"),
			CONSTRAINT "PK_dbkeepernet_version" PRIMARY KEY ("ID"),
			CONSTRAINT "FK_dbknetver_dbknetasm_id" FOREIGN KEY ("DBKEEPERNET_ASSEMBLY_ID") REFERENCES "DBKEEPERNET_ASSEMBLY"  ("ID")
        )
  		]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create sequence DBKEEPERNET_VERSION_SEQ" Id="5"
            MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Sequence DBKEEPERNET_VERSION_SEQ not found" Precondition="OraDbSequenceNotFound">
          <Param>DBKEEPERNET_VERSION_SEQ</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[CREATE sequence "DBKEEPERNET_VERSION_SEQ" ]]>
      </AlternativeStatement>
    </UpdateStep>
	    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create trigger BI_DBKEEPERNET_VERSION" Id="6"
            MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Trigger BI_DBKEEPERNET_VERSION not found" Precondition="DbTriggerNotFound">
          <Param>BI_DBKEEPERNET_VERSION</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[	
		CREATE trigger "BI_DBKEEPERNET_VERSION"  
		  before insert on "DBKEEPERNET_VERSION"              
		  for each row 
			begin  
				select "DBKEEPERNET_VERSION_SEQ".nextval into :NEW.ID from dual;
			end;
			
        ]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_step" Id="7"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_step not found" Precondition="DbTableNotFound">
          <Param>DBKEEPERNET_STEP</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[
        CREATE TABLE "DBKEEPERNET_STEP"
        (
        "ID"         NUMBER(10,0) NOT NULL,
        "DBKEEPERNET_VERSION_ID" NUMBER(10,0) NOT NULL,
        "STEP" NUMBER(10,0) NOT NULL,
        "CREATED" date not null,
        CONSTRAINT "UQ_dbkeepernet_step" UNIQUE ("DBKEEPERNET_VERSION_ID", "STEP"),
        CONSTRAINT "PK_dbkeepernet_step" PRIMARY KEY ("ID"),
        CONSTRAINT "FK_dbknetstep_dbknetver_id" FOREIGN KEY ("DBKEEPERNET_VERSION_ID") REFERENCES "DBKEEPERNET_VERSION" ("ID")
        )
        ]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create sequence DBKEEPERNET_STEP_SEQ" Id="8"
            MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Sequence DBKEEPERNET_STEP_SEQ not found" Precondition="OraDbSequenceNotFound">
          <Param>DBKEEPERNET_STEP_SEQ</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[CREATE sequence "DBKEEPERNET_STEP_SEQ" ]]>
    </AlternativeStatement>
  </UpdateStep>
  <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create trigger BI_DBKEEPERNET_STEP" Id="9"
        MarkAsExecuted="false">
    <Preconditions>
      <Precondition FriendlyName="Trigger BI_DBKEEPERNET_STEP not found" Precondition="DbTriggerNotFound">
        <Param>BI_DBKEEPERNET_STEP</Param>
      </Precondition>
    </Preconditions>
    <AlternativeStatement DbType="Oracle">
      <![CDATA[	
		CREATE trigger "BI_DBKEEPERNET_STEP"  
		  before insert on "DBKEEPERNET_STEP"              
		  for each row 
			begin  
				select "DBKEEPERNET_STEP_SEQ".nextval into :NEW.ID from dual;
			end;
			]]>
      </AlternativeStatement>
    </UpdateStep>
  </Update>
</upd:Updates>

=== DbKeeperNet/DbKeeperNet/DbKeeperNet.Extensions.MsSqlMembershipAndRolesSetup/Setup.xml
<?xml version="1.0" encoding="utf-8" ?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd"
             xmlns:asp="http://code.google.com/p/dbkeepernet/MsSqlMembershipAndRolesSetup-1.0.xsd"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="
                http://code.google.com/p/dbkeepernet/Updates-1.0.xsd ../DbKeeperNet.Engine/Resources/Updates-1.0.xsd
                http://code.google.com/p/dbkeepernet/MsSqlMembershipAndRolesSetup-1.0.xsd ./Resources/MsSqlMembershipAndRolesSetup-1.0.xsd"
                AssemblyName="DbUpdater.Engine.Membership">
  <DefaultPreconditions>
    <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
  </DefaultPreconditions>
  <Update Version="1.00">
    <UpdateStep xsi:type="asp:MsSqlMembershipAndRolesSetupType" Id="1" FriendlyName="Setting up database schema for membership and roles">
      <Preconditions>
        <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
        <Precondition FriendlyName="Database is MSSQL" Precondition="DbType">
          <Param>MSSQL</Param>
        </Precondition>
      </Preconditions>
    </UpdateStep>
  </Update>
</upd:Updates>

=== DbKeeperNet/DbKeeperNet/DbKeeperNet.Extensions.SQLite/SQLiteDatabaseServiceInstall.xml
<?xml version="1.0" encoding="utf-8" ?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd"
                	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	              xsi:schemaLocation="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd Updates-1.0.xsd"
                AssemblyName="DbKeeperNet.Engine">
  <DefaultPreconditions>
    <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
  </DefaultPreconditions>
  <Update Version="1.00">
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_assembly" Id="1"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_assembly not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_assembly</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="sqlite">
        CREATE TABLE dbkeepernet_assembly
        (
        id INTEGER NOT NULL,
        assembly TEXT NOT NULL,
        created TEXT NOT NULL,
        CONSTRAINT UQ_dbkeepernet_assembly UNIQUE (assembly),
        CONSTRAINT PK_dbkeepernet_assembly PRIMARY KEY (id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_version" Id="2"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_version not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_version</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="sqlite">
        CREATE TABLE dbkeepernet_version
        (
        id INTEGER NOT NULL,
        dbkeepernet_assembly_id INT NOT NULL,
        version TEXT not null,
        created TEXT not null,
        CONSTRAINT UQ_dbkeepernet_version UNIQUE (dbkeepernet_assembly_id, version),
        CONSTRAINT PK_dbkeepernet_version PRIMARY KEY (id),
        CONSTRAINT FK_dbknetver_dbknetasm_id FOREIGN KEY (dbkeepernet_assembly_id) REFERENCES dbkeepernet_assembly(id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_step" Id="3"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_step not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_step</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="sqlite">
        CREATE TABLE dbkeepernet_step
        (
        id INTEGER NOT NULL,
        dbkeepernet_version_id int not null,
        step int not null,
        created TEXT not null,
        CONSTRAINT UQ_dbkeepernet_step UNIQUE (dbkeepernet_version_id, step),
        CONSTRAINT PK_dbkeepernet_step PRIMARY KEY (id),
        CONSTRAINT FK_dbknetstep_dbknetver_id FOREIGN KEY (dbkeepernet_version_id) REFERENCES dbkeepernet_version(id)
        )
      </AlternativeStatement>
    </UpdateStep>
  </Update>
  <Update Version="2.00">
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_lock" Id="1">
      <AlternativeStatement DbType="sqlite">
        CREATE TABLE dbkeepernet_lock
        (
        id INTEGER NOT NULL,
        description TEXT NOT NULL,
        expiration TEXT NOT NULL,
        owner TEXT,
        CONSTRAINT PK_dbkeepernet_lock PRIMARY KEY (id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create lock record for database upgrade" Id="2">
      <AlternativeStatement DbType="sqlite">
        INSERT INTO dbkeepernet_lock(id, description, expiration) VALUES(5362, 'Database upgrade mutex', datetime('now', 'utc', '-1 minutes'))
      </AlternativeStatement>
    </UpdateStep>
  </Update>
</upd:Updates>

=== DbKeeperNet/DbKeeperNet/DbKeeperNet.SimpleDemo/DatabaseSetup.xml
<?xml version="1.0" encoding="utf-8"?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" AssemblyName="DbKeeperNet.SimpleDemo" xsi:schemaLocation="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd ../DbKeeperNet.Engine/Resources/Updates-1.0.xsd">
	<!-- Default way how to check whether to execute update step or not -->
	<DefaultPreconditions>
		<!-- We will use step information saving strategy -->
		<Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
	</DefaultPreconditions>
	<Update Version="1.00">
		<UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table DbKeeperNet_SimpleDemo" Id="1">
			<!-- DbType attribute may be ommited - it will result in default value all
           which means all database types -->
			<AlternativeStatement DbType="MsSql"><![CDATA[
          CREATE TABLE DbKeeperNet_SimpleDemo
          (
          id int identity(1, 1) not null,
          name nvarchar(32),
          constraint PK_DbKeeperNet_SimpleDemo primary key clustered (id)
          )
        ]]></AlternativeStatement>
			<AlternativeStatement DbType="MySql"><![CDATA[
          CREATE TABLE DbKeeperNet_SimpleDemo
          (
          id int not null auto_increment,
          name nvarchar(32),
          constraint PK_DbKeeperNet_SimpleDemo primary key (id)
          )
        ]]></AlternativeStatement>
			<AlternativeStatement DbType="PgSql"><![CDATA[
          CREATE TABLE DbKeeperNet_SimpleDemo
          (
          id serial not null,
          name varchar(32),
          constraint PK_DbKeeperNet_SimpleDemo primary key (id)
          )
        ]]></AlternativeStatement>
        <AlternativeStatement DbType="SQLite">
        <![CDATA[
        CREATE TABLE DbKeeperNet_SimpleDemo
          (
          id integer not null,
          name text,
          constraint PK_DbKeeperNet_SimpleDemo primary key (id)
          )
        ]]></AlternativeStatement>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[
        CREATE TABLE "DBKEEPERNET_SIMPLEDEMO"
        (
        "ID"         NUMBER(10,0) NOT NULL,
        "NAME"       VARCHAR2(32),
        CONSTRAINT "PK_DBKEEPERNET_SIMPLEDEMO" PRIMARY KEY ("ID")
        )
        ]]>
      </AlternativeStatement>
		</UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" Id="2" FriendlyName="Create sequence generator DBKEEPERNET_SIMPLEDEMO_SEQ">
      <AlternativeStatement DbType="Oracle">
        <![CDATA[CREATE sequence "DBKEEPERNET_SIMPLEDEMO_SEQ" ]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" Id="3" FriendlyName="Create identity trigger BI_DBKEEPERNET_SIMPLEDEMO">
      <AlternativeStatement DbType="Oracle">
        <![CDATA[CREATE trigger "BI_DBKEEPERNET_SIMPLEDEMO" 
		      before insert on "DBKEEPERNET_SIMPLEDEMO"
		      for each row 
			    begin  
				    select "DBKEEPERNET_SIMPLEDEMO_SEQ".nextval into :NEW.ID from dual;
			    end;]]>
      </AlternativeStatement>
    </UpdateStep>
		<UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Fill table DbKeeperNet_SimpleDemo" Id="4">
			<AlternativeStatement><![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('First value')
        ]]></AlternativeStatement>
		</UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Fill table DbKeeperNet_SimpleDemo" Id="5">
      <AlternativeStatement>
        <![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('Second value')
        ]]>
      </AlternativeStatement>
    </UpdateStep>
	</Update>
</upd:Updates>
