=== DbKeeperNet/DbKeeperNet/DbKeeperNet.Engine/Resources/Updates-1.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd" elementFormDefault="unqualified" xmlns="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd" xmlns:mstns="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
  <xs:element name="Updates">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Update" type="UpdateType" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="DefaultPreconditions" type="UpdatePreconditionCollectionType" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="AssemblyName" type="UpdateAssemblyNameType" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:complexType name="UpdateDbStepType">
    <xs:complexContent>
      <xs:extension base="UpdateStepBaseType">
        <xs:sequence>
          <xs:element name="AlternativeStatement" type="UpdateDbAlternativeStatementType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="UpdateDbAlternativeStatementType">
    <xs:simpleContent>
      <xs:extension base="UpdateDbStatementType">
        <xs:attribute name="Driver" type="xs:string" use="optional" default="all" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="UpdateType">
    <xs:sequence>
      <xs:element name="UpdateStep" type="UpdateStepBaseType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="Version" type="UpdateVersionType" use="required" />
    <xs:attribute name="FriendlyName" type="UpdateFriendlyNameType" />
  </xs:complexType>
  <xs:complexType name="CustomUpdateStepType">
    <xs:complexContent>
      <xs:extension base="UpdateStepBaseType">
        <xs:sequence>
          <xs:element name="Param" type="CustomUpdateStepParamType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="Type" type="UpdateClassType" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="UpdateStepBaseType" abstract="true">
    <xs:sequence>
      <xs:element name="Preconditions" type="UpdatePreconditionCollectionType" />
    </xs:sequence>
    <xs:attribute name="Id" type="UpdateStepIdType" use="required" />
    <xs:attribute name="FriendlyName" type="UpdateFriendlyNameType" use="optional" />
    <xs:attribute name="MarkAsExecuted" type="xs:boolean" default="true" />
  </xs:complexType>
  <xs:complexType name="PreconditionType">
    <xs:sequence>
      <xs:element name="Param" type="PreconditionParamType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="FriendlyName" type="UpdateFriendlyNameType" />
    <xs:attribute name="Precondition" type="xs:string" use="optional" default="NotExecuted" />
  </xs:complexType>
  <xs:simpleType name="UpdateAssemblyNameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
      <xs:maxLength value="64" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateVersionType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
      <xs:maxLength value="32" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateClassType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateStepIdType">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateDbStatementType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UpdateFriendlyNameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="UpdatePreconditionCollectionType">
    <xs:sequence>
      <xs:element name="Precondition" type="PreconditionType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PreconditionParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Name" type="xs:string" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CustomUpdateStepParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Name" type="xs:string" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== DbKeeperNet/DbKeeperNet/DbKeeperNet.Extensions.AspNetRolesAndMembership.Tests/AspNetMemberShipUpdate.xml
<?xml version="1.0" encoding="utf-8" ?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd"
                	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	              xsi:schemaLocation="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd ../DbKeeperNet.Engine/Resources/Updates-1.0.xsd"
                AssemblyName="DbUpdater.Engine.Membership">
  <DefaultPreconditions>
    <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
  </DefaultPreconditions>
  <Update Version="1.00">
    <UpdateStep xsi:type="upd:CustomUpdateStepType" Id="1" Type="DbKeeperNet.Engine.Windows.CustomUpdateSteps.MsSqlStepWithoutExplicitTransaction, DbKeeperNet.Engine.Windows"  FriendlyName="Setting up database schema for membership and roles">
      <Preconditions>
        <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
        <Precondition FriendlyName="Database is MSSQL" Precondition="DbType">
          <Param>MSSQL</Param>
        </Precondition>
      </Preconditions>
      <Param>DbKeeperNet.Extensions.MsSqlMembershipAndRolesSetup</Param>
      <Param>DbKeeperNet.Extensions.MsSqlMembershipAndRolesSetup.MsSqlMembershipAndRolesSetup.sql</Param>
    </UpdateStep>
  </Update>
</upd:Updates>

=== DbKeeperNet/DbKeeperNet/Demos/DbKeeperNet.AspNetMembershipDemo/DatabaseSetup.xml
<?xml version="1.0" encoding="utf-8"?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd" 
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" AssemblyName="DbKeeperNet.SimpleDemo" 
             xsi:schemaLocation="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd ../../DbKeeperNet.Engine/Resources/Updates-1.0.xsd"
             xmlns:asp="http://code.google.com/p/dbkeepernet/UpdatesAspNetRolesAndMembership-1.0.xsd"
             >
  <!-- Default way how to check whether to execute update step or not -->
  <DefaultPreconditions>
    <!-- We will use step information saving strategy -->
    <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
  </DefaultPreconditions>
  <Update Version="1.00">
    <!--
    This update step is needed to properly inject MSSQL membership schema into the database.
    The challenge here is that the schema setup must be executed in separated transaction.
    
    For other membership providers this is usually handled automatically upon the first usage
    (like for MySql)
    -->
    <UpdateStep xsi:type="upd:CustomUpdateStepType" Id="1" Type="DbKeeperNet.Engine.CustomUpdateSteps.MsSqlStepWithoutExplicitTransaction, DbKeeperNet.Engine"  FriendlyName="Setting up database schema for membership and roles">
      <Preconditions>
        <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
        <Precondition FriendlyName="Database is MSSQL" Precondition="DbType">
          <Param>MSSQL</Param>
        </Precondition>
      </Preconditions>
      <Param>DbKeeperNet.Extensions.MsSqlMembershipAndRolesSetup</Param>
      <Param>DbKeeperNet.Extensions.MsSqlMembershipAndRolesSetup.MsSqlMembershipAndRolesSetup.sql</Param>
    </UpdateStep>
    <!-- Create some seeded roles -->
    <UpdateStep xsi:type="asp:AspNetRoleCreateUpdateStepType" FriendlyName="Create role TestRole1" Id="2" RoleName="TestRole1"/>
    <UpdateStep xsi:type="asp:AspNetRoleCreateUpdateStepType" Id="3" RoleName="TestRole2"/>
    <!-- Seed an account and associate it with roles -->
    <UpdateStep xsi:type="asp:AspNetAccountCreateUpdateStepType" Id="4" UserName="TestUser1" Mail="testuser1@domain.com" Password="SeededPassword">
      <Role>TestRole1</Role>
      <Role>TestRole2</Role>
    </UpdateStep>
  </Update>
  <Update Version="1.01">
    <UpdateStep xsi:type="asp:AspNetAccountCreateUpdateStepType" Id="1" UserName="TestUser2" Mail="testuser2@domain.com" Password="SeededPassword2">
      <Role>TestRole1</Role>
    </UpdateStep>
    <!-- Delete the seeded role -->
    <UpdateStep xsi:type="asp:AspNetRoleDeleteUpdateStepType" Id="2" RoleName="TestRole2"/>
    <!-- Delete one of the seeded accounts -->
    <UpdateStep xsi:type="asp:AspNetAccountDeleteUpdateStepType" Id="3" UserName="TestUser1"/>
  </Update>
</upd:Updates>

=== DbKeeperNet/DbKeeperNet/DbKeeperNet.Extensions.Pgsql/PgSqlDatabaseServiceInstall.xml
<?xml version="1.0" encoding="utf-8" ?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd"
                	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	              xsi:schemaLocation="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd Updates-1.0.xsd"
                AssemblyName="DbKeeperNet.Engine">
  <DefaultPreconditions>
    <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
  </DefaultPreconditions>
  <Update Version="1.00">
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_assembly" Id="1"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_assembly not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_assembly</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="pgsql">
        CREATE TABLE dbkeepernet_assembly
        (
        id SERIAL NOT NULL,
        assembly varchar(255) NOT NULL,
        created time with time zone not null,
        CONSTRAINT UQ_dbkeepernet_assembly UNIQUE (assembly),
        CONSTRAINT PK_dbkeepernet_assembly PRIMARY KEY (id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_version" Id="2"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_version not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_version</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="pgsql">
        CREATE TABLE dbkeepernet_version
        (
        id serial NOT NULL,
        dbkeepernet_assembly_id int not null,
        version varchar(32) not null,
        created time with time zone not null,
        CONSTRAINT UQ_dbkeepernet_version UNIQUE (dbkeepernet_assembly_id, version),
        CONSTRAINT PK_dbkeepernet_version PRIMARY KEY (id),
        CONSTRAINT FK_dbknetver_dbknetasm_id FOREIGN KEY (dbkeepernet_assembly_id) REFERENCES dbkeepernet_assembly(id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_step" Id="3"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_step not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_step</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="pgsql">
        CREATE TABLE dbkeepernet_step
        (
        id serial NOT NULL,
        dbkeepernet_version_id int not null,
        step int not null,
        created time with time zone not null,
        CONSTRAINT UQ_dbkeepernet_step UNIQUE (dbkeepernet_version_id, step),
        CONSTRAINT PK_dbkeepernet_step PRIMARY KEY (id),
        CONSTRAINT FK_dbknetstep_dbknetver_id FOREIGN KEY (dbkeepernet_version_id) REFERENCES dbkeepernet_version(id)
        )
      </AlternativeStatement>
    </UpdateStep>
  </Update>
</upd:Updates>

=== DbKeeperNet/DbKeeperNet/Demos/DbKeeperNet.ComplexDemo/DatabaseSetupPart1.xml
<?xml version="1.0" encoding="utf-8" ?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd"
                	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	              xsi:schemaLocation="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd ../../DbKeeperNet.Engine/Resources/Updates-1.0.xsd"
                AssemblyName="DbKeeperNet.ComplexDemo">
  <!-- Default way how to check whether to execute update step or not -->
  <DefaultPreconditions>
    <!-- We will use step information saving strategy -->
    <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
  </DefaultPreconditions>

  <Update Version="1.00">
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table DbKeeperNet_SimpleDemo" Id="1">
      <AlternativeStatement DbType="MsSql">
        <![CDATA[
          CREATE TABLE DbKeeperNet_SimpleDemo
          (
          id int identity(1, 1) not null,
          name nvarchar(32),
          constraint PK_DbKeeperNet_SimpleDemo primary key clustered (id)
          )
        ]]>
      </AlternativeStatement>
      <AlternativeStatement DbType="MySql">
        <![CDATA[
          CREATE TABLE DbKeeperNet_SimpleDemo
          (
          id int not null auto_increment,
          name nvarchar(32),
          constraint PK_DbKeeperNet_SimpleDemo primary key (id)
          )
        ]]>
      </AlternativeStatement>
      <AlternativeStatement DbType="PgSql">
        <![CDATA[
          CREATE TABLE DbKeeperNet_SimpleDemo
          (
          id serial not null,
          name varchar(32),
          constraint PK_DbKeeperNet_SimpleDemo primary key (id)
          )
        ]]>
      </AlternativeStatement>
      <AlternativeStatement DbType="SQLite">
        <![CDATA[
          CREATE TABLE DbKeeperNet_SimpleDemo
          (
          id integer not null,
          name text,
          constraint PK_DbKeeperNet_SimpleDemo primary key (id)
          )
        ]]>
      </AlternativeStatement>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[
        CREATE TABLE "DBKEEPERNET_SIMPLEDEMO"
        (
        "ID"         NUMBER(10,0) NOT NULL,
        "NAME"       VARCHAR2(32),
        CONSTRAINT "PK_DBKEEPERNET_SIMPLEDEMO" PRIMARY KEY ("ID")
        )
        ]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" Id="2" FriendlyName="Create sequence generator DBKEEPERNET_SIMPLEDEMO_SEQ">
      <AlternativeStatement DbType="Oracle">
        <![CDATA[CREATE sequence "DBKEEPERNET_SIMPLEDEMO_SEQ" ]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" Id="3" FriendlyName="Create identity trigger BI_DBKEEPERNET_SIMPLEDEMO">
      <AlternativeStatement DbType="Oracle">
        <![CDATA[CREATE trigger "BI_DBKEEPERNET_SIMPLEDEMO" 
		      before insert on "DBKEEPERNET_SIMPLEDEMO"
		      for each row 
			    begin  
				    select "DBKEEPERNET_SIMPLEDEMO_SEQ".nextval into :NEW.ID from dual;
			    end;]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:CustomUpdateStepType" Id="4" Type="DbKeeperNet.ComplexDemo.ComplexDemoCustomStep,DbKeeperNet.ComplexDemo">
      <Param>Hellow world</Param>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Fill table DbKeeperNet_SimpleDemo" Id="5">
      <AlternativeStatement DbType="MsSql">
        <![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('First value MS SQL');
          insert into DbKeeperNet_SimpleDemo(name) values('Second value MS SQL');
        ]]>
      </AlternativeStatement>
      <AlternativeStatement DbType="MySql">
        <![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('First value MySQL');
          insert into DbKeeperNet_SimpleDemo(name) values('Second value MySQL');
        ]]>
      </AlternativeStatement>
      <AlternativeStatement DbType="PgSql">
        <![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('First value PostgreSQL');
          insert into DbKeeperNet_SimpleDemo(name) values('Second value PostgreSQL');
        ]]>
      </AlternativeStatement>
      <AlternativeStatement DbType="SQLite">
        <![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('First value SQLite');
          insert into DbKeeperNet_SimpleDemo(name) values('Second value SQLite');
        ]]>
      </AlternativeStatement>
      <AlternativeStatement DbType="Oracle">
        <![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('First value Oracle')
        ]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" Id="6">
      <AlternativeStatement DbType="Oracle">
        <![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('Second value Oracle')
        ]]>
      </AlternativeStatement>
    </UpdateStep>
  </Update>
  <Update Version="2.00">
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Fill table DbKeeperNet_SimpleDemo" Id="1">
      <AlternativeStatement>
        <![CDATA[
          insert into DbKeeperNet_SimpleDemo(name) values('Third value')
        ]]>
      </AlternativeStatement>
    </UpdateStep>
  </Update>
</upd:Updates>

=== DbKeeperNet/DbKeeperNet/DbKeeperNet.Extensions.SqlServer/MsSqlDatabaseServiceInstall.xml
<?xml version="1.0" encoding="utf-8" ?>
<upd:Updates xmlns:upd="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd"
                	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	              xsi:schemaLocation="http://code.google.com/p/dbkeepernet/Updates-1.0.xsd Updates-1.0.xsd"
                AssemblyName="DbKeeperNet.Engine">
  <DefaultPreconditions>
    <Precondition FriendlyName="Update step executed" Precondition="StepNotExecuted"/>
  </DefaultPreconditions>
  <Update Version="1.00">
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_assembly" Id="1"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_assembly not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_assembly</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="MsSql">
        CREATE TABLE dbkeepernet_assembly
        (
        id int identity(1,1)  NOT NULL,
        assembly varchar(255) NOT NULL,
        created datetime not null,
        CONSTRAINT UQ_dbkeepernet_assembly UNIQUE (assembly),
        CONSTRAINT PK_dbkeepernet_assembly PRIMARY KEY CLUSTERED (id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_version" Id="2"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_version not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_version</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="MsSql">
        CREATE TABLE dbkeepernet_version
        (
        id int identity(1,1)  NOT NULL,
        dbkeepernet_assembly_id int not null,
        version varchar(32) not null,
        created datetime not null,
        CONSTRAINT UQ_dbkeepernet_version UNIQUE (dbkeepernet_assembly_id, version),
        CONSTRAINT PK_dbkeepernet_version PRIMARY KEY CLUSTERED (id),
        CONSTRAINT FK_dbknetver_dbknetasm_id FOREIGN KEY (dbkeepernet_assembly_id) REFERENCES dbkeepernet_assembly(id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_step" Id="3"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Table dbkeepernet_step not found" Precondition="DbTableNotFound">
          <Param>dbkeepernet_step</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="MsSql">
        CREATE TABLE dbkeepernet_step
        (
        id int identity(1,1)  NOT NULL,
        dbkeepernet_version_id int not null,
        step int not null,
        created datetime not null,
        CONSTRAINT UQ_dbkeepernet_step UNIQUE (dbkeepernet_version_id, step),
        CONSTRAINT PK_dbkeepernet_step PRIMARY KEY CLUSTERED (id),
        CONSTRAINT FK_dbknetstep_dbknetver_id FOREIGN KEY (dbkeepernet_version_id) REFERENCES dbkeepernet_version(id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create procedure DbKeeperNetIsStepExecuted" Id="4"
                MarkAsExecuted="false">
      <Preconditions>
        <Precondition FriendlyName="Procedure DbKeeperNetIsStepExecuted not found" Precondition="DbProcedureNotFound">
          <Param>DbKeeperNetIsStepExecuted</Param>
        </Precondition>
      </Preconditions>
      <AlternativeStatement DbType="MsSql">
        <![CDATA[
        CREATE PROCEDURE DbKeeperNetIsStepExecuted
        -- Add the parameters for the stored procedure here
        @assembly varchar(255),
        @version varchar(32),
        @step int
        AS
        BEGIN
        -- SET NOCOUNT ON added to prevent extra result sets from
        -- interfering with SELECT statements.
        SET NOCOUNT ON;

        declare @result bit;

        -- should be 0 or 1
        select @result = count(version)  from dbkeepernet_assembly asm
          join dbkeepernet_version ver on asm.id = ver.dbkeepernet_assembly_id
          join dbkeepernet_step step on ver.id = step.dbkeepernet_version_id
		      where step.step = @step 
                and ver.version = @version and 
                asm.assembly = @assembly;
                
        select @result;
        END
        ]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create procedure DbKeeperNetSetStepExecuted" Id="5">
      <AlternativeStatement DbType="MsSql">
        <![CDATA[
          CREATE PROCEDURE DbKeeperNetSetStepExecuted
          -- Add the parameters for the stored procedure here
          @assembly varchar(255),
          @version varchar(32),          @step int
          AS
          BEGIN
          -- SET NOCOUNT ON added to prevent extra result sets from
          -- interfering with SELECT statements.
          SET NOCOUNT ON;

          declare @assemblyId int;
          declare @versionId int;
          declare @stepId int;

          select @assemblyId = id from dbkeepernet_assembly where assembly = @assembly;
          if (@assemblyId is null)
          begin
          insert into dbkeepernet_assembly(assembly, created) values(@assembly, GETUTCDATE());
          select @assemblyId = @@IDENTITY;
          end

          select @versionId = id from dbkeepernet_version where dbkeepernet_assembly_id = @assemblyId and version = @version;
          if (@versionId is null)
          begin
          insert into dbkeepernet_version(dbkeepernet_assembly_id, version, created) values(@assemblyId, @version, GETUTCDATE());
          select @versionId = @@IDENTITY;
          end

          select @stepId = id from dbkeepernet_step where dbkeepernet_version_id = @versionId and step = @step;
          if (@stepId is null)
          begin
          insert into dbkeepernet_step(dbkeepernet_version_id, step, created) values(@versionId, @step, GETUTCDATE());
          end
          END

        ]]>
      </AlternativeStatement>
    </UpdateStep>
  </Update>
  <Update Version="2.00">
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create table dbkeepernet_lock" Id="1">
      <AlternativeStatement DbType="MsSql">
        CREATE TABLE dbkeepernet_lock
        (
        id int NOT NULL,
        description nvarchar(32) NOT NULL,
        expiration datetime2 NOT NULL,
        ownerDescription nvarchar(128),
        CONSTRAINT PK_dbkeepernet_lock PRIMARY KEY (id)
        )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create lock record for database upgrade" Id="2">
      <AlternativeStatement DbType="MsSql">
        INSERT INTO dbkeepernet_lock(id, description, expiration) VALUES(5362, 'Database upgrade mutex', DATEADD(mi, -1, GETUTCDATE()) )
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create procedure DbKeeperNetReleaseLock" Id="3">
      <AlternativeStatement DbType="MsSql">
        <![CDATA[
        CREATE PROCEDURE DbKeeperNetReleaseLock
        @id int
        AS
        BEGIN
        UPDATE dbkeepernet_lock SET expiration = DATEADD(mi, -1, GETUTCDATE()), ownerDescription = null WHERE id = @id
        END
        ]]>
      </AlternativeStatement>
    </UpdateStep>
    <UpdateStep xsi:type="upd:UpdateDbStepType" FriendlyName="Create procedure DbKeeperNetAcquireLock" Id="4">
      <AlternativeStatement DbType="MsSql">
        <![CDATA[
        CREATE PROCEDURE DbKeeperNetAcquireLock
        @id int,
        @ownerDescription nvarchar(128),
        @expiration int
        AS
        BEGIN
        BEGIN TRANSACTION

        UPDATE dbkeepernet_lock SET expiration = DATEADD(mi, @expiration, GETUTCDATE()), ownerDescription = @ownerDescription 
          WHERE id = @id AND expiration < GETUTCDATE()

        IF @@ROWCOUNT = 0
        BEGIN
          SELECT id, description, ownerDescription, expiration FROM dbkeepernet_lock WHERE id = @id
        END
        
        COMMIT

        END
        ]]>
      </AlternativeStatement>
    </UpdateStep>
  </Update>
</upd:Updates>
